var age_slider = document.getElementById("age");
var age_output = document.getElementById("age_output");
age_output.innerHTML = "Age: " + age_slider.value; 

age_slider.oninput = function() {
    age_output.innerHTML = "Age: " + this.value;
    survival_chance();

}

var class_slider = document.getElementById("passenger_class");
var class_output = document.getElementById("passenger_class_output");
class_output.innerHTML = "Passenger class: " + class_slider.value; 

class_slider.oninput = function() {
    class_output.innerHTML = "Passenger class: " + this.value;
    survival_chance();
}

var gender = document.getElementById("sex");

gender.oninput = function() {
    console.log(gender.value)
    survival_chance();

}



// Weights + bias generated by machine learning
const WEIGHTS = [-0.28483392, -1.1464562, 0.00149105];
const BIAS = 0.773179449079725

var survival_output = document.getElementById("survival_chance");
survival_chance();

function survival_chance () {
    var x = parseInt(class_slider.value) * WEIGHTS[0] + parseInt(gender.value) * WEIGHTS[1] + parseFloat(age_slider.value) * WEIGHTS[2] + BIAS;
    console.log(x)
    console.log(survival_output)
    survival_output.innerHTML = "Chance of survival: " + String(Math.round(1/(1+Math.exp(-x)) * 100)) + "%";
}